baseURL = "/"
languageCode = "en-us"
title = "Voz de Esperanza"
theme = "custom"

[params]
  description = "Empowering communities through sustainable initiatives."

[permalinks]
  page = "/:title/"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[module]
  [[module.mounts]]
    source = "themes/custom/assets"
    target = "assets"
  [[module.mounts]]
    source = "themes/custom/static"
    target = "static"
